services:
  cache:
    image: valkey/valkey:8.1
    container_name: neat_cache
    restart: always
    ports:
      - '6379:6379'
  db:
    image: postgres:17
    container_name: neat_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: neat_usr
      POSTGRES_PASSWORD: neat_password
      POSTGRES_DB: neat_db
  monitoring:
    image: grafana/otel-lgtm:latest
    container_name: neat_monitoring
    restart: always
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
  bugsink:
    image: bugsink/bugsink:latest
    container_name: neat_bugsink
    restart: always
    ports:
      - "9000:9000"
    environment:
      SECRET_KEY: QToKz8lBDnzBPr5uoVHargQ1xjekWzEs0F6IYc7O0M1PJIaFWQ
      CREATE_SUPERUSER: admin:admin
      PORT: 9000