/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DashboardUserRouteImport } from './routes/dashboard/user'
import { Route as DashboardRoleRouteImport } from './routes/dashboard/role'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardAboutRouteImport } from './routes/dashboard/about'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsSandboxRouteImport } from './routes/dashboard/settings/sandbox'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardUserRoute = DashboardUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRoleRoute = DashboardRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAboutRoute = DashboardAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSandboxRoute =
  DashboardSettingsSandboxRouteImport.update({
    id: '/settings/sandbox',
    path: '/settings/sandbox',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/role': typeof DashboardRoleRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/': typeof PublicIndexRoute
  '/dashboard/settings/sandbox': typeof DashboardSettingsSandboxRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/role': typeof DashboardRoleRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/': typeof PublicIndexRoute
  '/dashboard/settings/sandbox': typeof DashboardSettingsSandboxRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/role': typeof DashboardRoleRoute
  '/dashboard/user': typeof DashboardUserRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/settings/sandbox': typeof DashboardSettingsSandboxRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/about'
    | '/dashboard/account'
    | '/dashboard/library'
    | '/dashboard/role'
    | '/dashboard/user'
    | '/'
    | '/dashboard/settings/sandbox'
    | '/dashboard/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/about'
    | '/dashboard/account'
    | '/dashboard/library'
    | '/dashboard/role'
    | '/dashboard/user'
    | '/'
    | '/dashboard/settings/sandbox'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/_public'
    | '/auth'
    | '/dashboard'
    | '/_public/about'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/about'
    | '/dashboard/account'
    | '/dashboard/library'
    | '/dashboard/role'
    | '/dashboard/user'
    | '/_public/'
    | '/dashboard/settings/sandbox'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/user': {
      id: '/dashboard/user'
      path: '/user'
      fullPath: '/dashboard/user'
      preLoaderRoute: typeof DashboardUserRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/role': {
      id: '/dashboard/role'
      path: '/role'
      fullPath: '/dashboard/role'
      preLoaderRoute: typeof DashboardRoleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/sandbox': {
      id: '/dashboard/settings/sandbox'
      path: '/settings/sandbox'
      fullPath: '/dashboard/settings/sandbox'
      preLoaderRoute: typeof DashboardSettingsSandboxRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardRoleRoute: typeof DashboardRoleRoute
  DashboardUserRoute: typeof DashboardUserRoute
  DashboardSettingsSandboxRoute: typeof DashboardSettingsSandboxRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardRoleRoute: DashboardRoleRoute,
  DashboardUserRoute: DashboardUserRoute,
  DashboardSettingsSandboxRoute: DashboardSettingsSandboxRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
